import { FormEvent, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import type { BetaCampaign, Product, ProductEnvironment } from '../lib/types';

export function Beta() {
  const [campaigns, setCampaigns] = useState<BetaCampaign[]>([]); const [products, setProducts] = useState<Product[]>([]); const [environments, setEnvironments] = useState<ProductEnvironment[]>([]);
  const [productId, setProductId] = useState(''); const [environmentId, setEnvironmentId] = useState(''); const [name, setName] = useState(''); const [max, setMax] = useState('5'); const [error, setError] = useState('');
  const load = async () => { try { const p = await api.products(); setProducts(p); setCampaigns(await api.betaCampaigns()); setEnvironments((await Promise.all(p.map(x => api.environments(x.id)))).flat()); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { void load(); }, []);
  async function create(e: FormEvent) { e.preventDefault(); try { await api.createBetaCampaign({ productId, environmentId, name, description: null, maxInvitations: Number(max), startsAtUtc: null, endsAtUtc: null }); setName(''); await load(); } catch (e) { setError((e as Error).message); } }
  const productName = (id: string) => products.find(p => p.id === id)?.name ?? id;
  return <section><div className="page-heading"><div><p className="eyebrow">Orchestration</p><h2>Beta Management</h2></div></div>{error && <p className="error">{error}</p>}<div className="grid"><div className="card"><h3>Campaigns</h3>{campaigns.length === 0 ? <p className="muted">No beta campaigns yet.</p> : <ul className="rows">{campaigns.map(c => <li key={c.id}><div><Link to={`/beta/campaigns/${c.id}`}>{c.name}</Link><span>{productName(c.productId)} · {environments.find(e => e.id === c.environmentId)?.name ?? c.environmentId} · {c.totalInvitations}/{c.maxInvitations} used</span></div><span className={`status ${c.status.toLowerCase()}`}>{c.status}</span></li>)}</ul>}</div><form className="card form" onSubmit={create}><h3>Create campaign</h3><select required value={productId} onChange={e => { setProductId(e.target.value); setEnvironmentId(''); }}><option value="">Select product</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select required value={environmentId} onChange={e => setEnvironmentId(e.target.value)} disabled={!productId}><option value="">Select target environment</option>{environments.filter(x => x.productId === productId).map(x => <option key={x.id} value={x.id}>{x.name} ({x.environmentType})</option>)}</select><input required placeholder="Campaign name" value={name} onChange={e => setName(e.target.value)}/><input required min="1" type="number" placeholder="Maximum invitations" value={max} onChange={e => setMax(e.target.value)}/><button type="submit">Create draft</button></form></div></section>;
}
