import { FormEvent, useEffect, useState } from 'react'; import { Link, useParams } from 'react-router-dom'; import { api, environmentTypeValues, connectionTypeValues } from '../lib/api'; import { statusClass, statusLabel } from '../lib/status'; import type { ConnectionType, EnvironmentType, Product, ProductConnection, ProductEnvironment } from '../lib/types';

export function ProductDetail() {
  const { id = '' } = useParams(); const [product, setProduct] = useState<Product>(); const [envs, setEnvs] = useState<ProductEnvironment[]>([]); const [error, setError] = useState('');
  const [editing, setEditing] = useState(false); const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [description, setDescription] = useState('');
  const load = async () => { try { const p = await api.product(id); setProduct(p); setName(p.name); setSlug(p.slug); setDescription(p.description ?? ''); setEnvs(await api.environments(id)); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { void load(); }, [id]);
  async function saveProduct(e: FormEvent) { e.preventDefault(); try { await api.updateProduct(id, { name, slug, description: description || null }); setEditing(false); await load(); } catch (e) { setError((e as Error).message); } }
  async function archiveProduct() { if (!window.confirm('Deactivate this product?')) return; try { await api.deleteProduct(id); await load(); } catch (e) { setError((e as Error).message); } }
  if (!product) return <section><p>{error || 'Loading…'}</p></section>;
  return <section><Link to="/products">← Products</Link><div className="page-heading"><div><p className="eyebrow">Product</p><h2>{product.name}</h2><p className="muted">{product.slug} · <span className={`status ${statusClass(product.status)}`}>{statusLabel(product.status)}</span></p></div><div className="actions"><button onClick={() => setEditing(v => !v)}>{editing ? 'Cancel' : 'Edit product'}</button><button className="danger" onClick={archiveProduct}>Deactivate</button></div></div>{error && <p className="error">{error}</p>}{editing && <form className="card form product-edit" onSubmit={saveProduct}><input required value={name} onChange={e => setName(e.target.value)}/><input required value={slug} onChange={e => setSlug(e.target.value)}/><textarea value={description} onChange={e => setDescription(e.target.value)}/><button type="submit">Save changes</button></form>}<div className="card"><h3>Environments</h3>{envs.map(environment => <EnvironmentCard key={environment.id} productId={id} environment={environment} onChanged={load} onError={setError}/>)}{envs.length === 0 && <p className="muted">No environments yet. Add Development, Staging, or Production below.</p>}</div><CreateEnvironmentForm productId={id} onCreated={load} onError={setError}/></section>;
}

function CreateEnvironmentForm({ productId, onCreated, onError }: { productId: string; onCreated: () => void; onError: (message: string) => void }) { const [name, setName] = useState(''); const [type, setType] = useState<EnvironmentType>('Development'); const [url, setUrl] = useState(''); async function submit(e: FormEvent) { e.preventDefault(); try { await api.createEnvironment(productId, { name, environmentType: type, baseUrl: url }); setName(''); setUrl(''); onCreated(); } catch (e) { onError((e as Error).message); } } return <form className="card form" onSubmit={submit}><h3>Add environment</h3><input required placeholder="Name" value={name} onChange={e => setName(e.target.value)}/><select value={type} onChange={e => setType(e.target.value as EnvironmentType)}>{environmentTypeValues.map(value => <option key={value}>{value}</option>)}</select><input required placeholder="https://..." value={url} onChange={e => setUrl(e.target.value)}/><button type="submit">Create environment</button></form>; }

function EnvironmentCard({ productId, environment, onChanged, onError }: { productId: string; environment: ProductEnvironment; onChanged: () => void; onError: (message: string) => void }) {
  const [editing, setEditing] = useState(false); const [name, setName] = useState(environment.name); const [type, setType] = useState<EnvironmentType>(environment.environmentType); const [url, setUrl] = useState(environment.baseUrl); const [connections, setConnections] = useState<ProductConnection[]>([]); const [secretReference, setSecretReference] = useState(''); const [accessIdReference, setAccessIdReference] = useState(''); const [accessSecretReference, setAccessSecretReference] = useState(''); const [connectionType, setConnectionType] = useState<ConnectionType>('InternalApi'); const [health, setHealth] = useState(''); const [editingConnectionId, setEditingConnectionId] = useState<string>();
  useEffect(() => { api.connections(productId, environment.id).then(setConnections).catch(() => undefined); }, [productId, environment.id]);
  async function save() { try { await api.updateEnvironment(productId, environment.id, { name, environmentType: type, baseUrl: url }); setEditing(false); onChanged(); } catch (e) { onError((e as Error).message); } }
  async function remove() { if (!window.confirm('Delete this environment? Existing connections must be removed first.')) return; try { await api.deleteEnvironment(productId, environment.id); onChanged(); } catch (e) { onError((e as Error).message); } }
  async function check() { try { const result = await api.healthCheck(productId, environment.id); setHealth(`${result.status}${result.latencyMs === undefined ? '' : ` · ${result.latencyMs} ms`}${result.message ? ` · ${result.message}` : ''}`); onChanged(); } catch (e) { onError((e as Error).message); } }
  function clearConnectionForm() { setSecretReference(''); setAccessIdReference(''); setAccessSecretReference(''); setEditingConnectionId(undefined); }
  function editConnection(connection: ProductConnection) { setEditingConnectionId(connection.id); setConnectionType(connection.connectionType); setSecretReference(connection.secretReference); setAccessIdReference(connection.accessClientIdSecretReference ?? ''); setAccessSecretReference(connection.accessClientSecretSecretReference ?? ''); }
  async function saveConnection(e: FormEvent) { e.preventDefault(); const body = { connectionType, secretReference, accessClientIdSecretReference: accessIdReference || null, accessClientSecretSecretReference: accessSecretReference || null, isEnabled: true }; try { const connection = editingConnectionId ? await api.updateConnection(productId, environment.id, editingConnectionId, body) : await api.createConnection(productId, environment.id, body); setConnections(current => editingConnectionId ? current.map(c => c.id === connection.id ? connection : c) : [...current, connection]); clearConnectionForm(); } catch (e) { onError((e as Error).message); } }
  async function removeConnection(connectionId: string) { if (!window.confirm('Delete this connection reference?')) return; try { await api.deleteConnection(productId, environment.id, connectionId); setConnections(current => current.filter(c => c.id !== connectionId)); } catch (e) { onError((e as Error).message); } }
  return <div className="environment"><div className="environment-heading"><div><strong>{environment.name}</strong><span>{environment.environmentType} · <span className={`status ${statusClass(environment.status)}`}>{statusLabel(environment.status)}</span></span><small>{environment.baseUrl}</small></div><div className="actions"><button onClick={() => setEditing(v => !v)}>{editing ? 'Cancel' : 'Edit'}</button><button onClick={check}>Check health</button><button className="danger" onClick={remove}>Delete</button></div></div>{health && <p className="health-result">{health}</p>}{editing && <div className="inline-form"><input value={name} onChange={e => setName(e.target.value)}/><select value={type} onChange={e => setType(e.target.value as EnvironmentType)}>{environmentTypeValues.map(value => <option key={value}>{value}</option>)}</select><input value={url} onChange={e => setUrl(e.target.value)}/><button onClick={save}>Save</button></div>}<div className="connection-box"><strong>Connections</strong>{connections.map(c => <div className="connection" key={c.id}><span>{c.connectionType} · {c.secretReference} · {c.isEnabled ? 'Enabled' : 'Disabled'}{c.accessClientIdSecretReference && ' · Cloudflare Access configured'}</span><button onClick={() => editConnection(c)}>Edit</button><button onClick={() => removeConnection(c.id)}>Remove</button></div>)}<form className="inline-form" onSubmit={saveConnection}><select value={connectionType} onChange={e => setConnectionType(e.target.value as ConnectionType)}>{connectionTypeValues.map(value => <option key={value}>{value}</option>)}</select><input required placeholder="Control key secret reference name" value={secretReference} onChange={e => setSecretReference(e.target.value)}/><input placeholder="Cloudflare Access Client ID secret reference name (optional)" value={accessIdReference} onChange={e => setAccessIdReference(e.target.value)}/><input placeholder="Cloudflare Access Client Secret secret reference name (optional)" value={accessSecretReference} onChange={e => setAccessSecretReference(e.target.value)}/><small>Enter reference names only; actual secrets are resolved securely by the server. Configure both Cloudflare references or leave both blank.</small><button type="submit">{editingConnectionId ? 'Save connection' : 'Add connection'}</button>{editingConnectionId && <button type="button" onClick={clearConnectionForm}>Cancel</button>}</form></div></div>; }
